# Generated by Django 5.0.1 on 2024-01-29 17:55

import apps.test_models.db_helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_started',
            field=models.DateTimeField(help_text='ДАТА, КОГДА ЗАДАЧА БЫЛА СОЗДАНА'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(default='Здесь может быть ваше описание к задаче', max_length=1000),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(default=apps.test_models.db_helpers.generate_default_title, max_length=75, verbose_name='НАЗВАНИЕ ЗАДАЧИ'),
        ),
    ]
