# Generated by Django 5.0.1 on 2024-01-29 18:05

import apps.test_models.db_helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_models', '0002_alter_task_date_started_alter_task_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(default=apps.test_models.db_helpers.generate_default_title, max_length=75, unique=True, verbose_name='НАЗВАНИЕ ЗАДАЧИ'),
        ),
    ]
