# Generated by Django 5.0.1 on 2024-01-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_models', '0003_alter_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(default='Здесь может быть ваше описание к задаче', max_length=1000, unique_for_date='date_started'),
        ),
    ]
