# Generated by Django 5.0.1 on 2024-01-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_models', '0006_alter_task_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_started',
            field=models.DateTimeField(auto_now_add=True, help_text='ДАТА, КОГДА ЗАДАЧА БЫЛА СОЗДАНА'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
